require 'yaml'

class StaffsController < ApplicationController
  before_action :user_identify
  # account: a1234567 password: secret

  def dashboard
    @staffs = current_user
  end

  def appointment
    #
  end

  def history
    # List of all advice that were generated by different students ordered by the latest ones first
    @advices = CourseAdvice.order(created_at: :desc)
  end

  def show
    # for showing detail of each advice with course details
    @id = params[:advice_id] || session[:id]
    @advices = CourseAdvice.where(advice_ID: @id)
    if params[:advice_id]
      session[:id] = params[:advice_id]
    end

    @advices.each do |advice|
      @a_ID = advice.advice_ID
      @date = advice.date
      @note = advice.note

      @year = advice.degree_year
      @teaching_period = advice.teaching_period

      @s_ID = advice.student_ID
      @enrolments=Enrolment.where(student_ID: @s_ID)
      student_details = Student.where(account: @s_ID)
      student_details.each do |student|
        @name = student.name
        @residency = student.residency
        @program = student.program
        @plan = student.plan
        @s_year = student.year
        @expected_completion = student.expected_completion
        unless student.english_exam.nil?
          @english_exam = student.english_exam
          @english_score = student.english_score
        end
      end

      raw_course_IDs = advice.course_ID
      @course_IDs = YAML.load(raw_course_IDs.delete': ')

    end

    @selected_core_courses = Program.list_program_courses("core", @course_IDs, false, year: @year,teaching_period: @teaching_period)
    @selected_electives = Program.list_program_courses("elective", @course_IDs, false, year: @year,teaching_period: @teaching_period)

  end

  def help
    # just for help
  end


  private
    def user_identify
      if current_user.is_a?(Staff)
        #it's an instance of staff
      else
        redirect_to root_url, :alert => "You must login as staff to view this resource"
      end
    end
  end
